server:
  port: 8080
  servlet:
    context-path: /pig-chat

# mybatis
mybatis:
  type-aliases-package: com.chat.pig.entity
  mapper-locations: classpath:mapper/*.xml

# mapper
mapper:
  mappers: com.chat.pig.utils.MyMapper
  not-empty: false
  identity: MYSQL

spring:
  datasource:
    # 数据源
    url: jdbc:mysql://127.0.0.1:3306/chat?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 连接池
    hikari:
      maximum-pool-size: 8
      minimum-idle: 4
      idle-timeout: 30000
      connection-timeout: 30000
      max-lifetime: 45000
      auto-commit: true
      pool-name: couponHikariCP